force-app/main/default/objects/Account/recordTypes/Distributor.recordType-meta.xml
<RecordType>
    <fullName>Distributor</fullName>
    <active>true</active>
    <label>Distributor</label>
</RecordType>

force-app/main/default/objects/Distributor_Document__c/Distributor_Document__c.object-meta.xml
<CustomObject>
    <label>Distributor Document</label>
    <nameField>
        <label>Distributor Document Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Distributor Documents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Distributor_Document__c/fields/Distributor__c.field-meta.xml
<CustomField>
    <fullName>Distributor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Distributor</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Distributor Documents</relationshipLabel>
    <relationshipName>Distributor_Documents</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Distributor_Document__c/fields/Document_Type__c.field-meta.xml
<CustomField>
    <fullName>Document_Type__c</fullName>
    <label>Document Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Photograph (Owner)</fullName>
            </value>
            <value>
                <fullName>Photograph (Shop)</fullName>
            </value>
            <value>
                <fullName>PAN Card</fullName>
            </value>
            <value>
                <fullName>Demand Draft(DD)</fullName>
            </value>
            <value>
                <fullName>Dealer booklet</fullName>
            </value>
            <value>
                <fullName>Annexure of declaration of relation</fullName>
                <isActive>false</isActive>
                <label>Annexure of declaration of relation</label>
            </value>
            <value>
                <fullName>Annexure of declaration of signing documents</fullName>
                <isActive>false</isActive>
                <label>Annexure of declaration of signing documents</label>
            </value>
            <value>
                <fullName>Blank Letter Pad for Address Proof</fullName>
                <isActive>false</isActive>
                <label>Blank Letter Pad for Address Proof</label>
            </value>
            <value>
                <fullName>Copy of Partnership Firm/ Company/HUF/Prop. Affidavit</fullName>
                <isActive>false</isActive>
                <label>Copy of Partnership Firm/ Company/HUF/Prop. Affidavit</label>
            </value>
            <value>
                <fullName>Copy of Pesticide / Seed License</fullName>
                <isActive>false</isActive>
                <label>Copy of Pesticide / Seed License</label>
            </value>
            <value>
                <fullName>GST Certificate</fullName>
                <isActive>false</isActive>
                <label>GST Certificate</label>
            </value>
            <value>
                <fullName>Latest bank statement of last 3 months</fullName>
                <isActive>false</isActive>
                <label>Latest bank statement of last 3 months</label>
            </value>
            <value>
                <fullName>Owner/PARTNERs/Director ADHAAR Copy</fullName>
                <isActive>false</isActive>
                <label>Owner/PARTNERs/Director ADHAAR Copy</label>
            </value>
            <value>
                <fullName>Photograph (Selfie with Customer)</fullName>
                <isActive>false</isActive>
                <label>Photograph (Selfie with Customer)</label>
            </value>
            <value>
                <fullName>Residential Address Proof Proprietor/Partner/Director</fullName>
                <isActive>false</isActive>
                <label>Residential Address Proof Proprietor/Partner/Director</label>
            </value>
            <value>
                <fullName>Scanned Security Cheque</fullName>
                <isActive>false</isActive>
                <label>Scanned Security Cheque</label>
            </value>
            <value>
                <fullName>Signed Business Policy</fullName>
                <isActive>false</isActive>
                <label>Signed Business Policy</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/DistributorOnboardingController.cls
/**  
* @description       : This class used to Upload Documents against Account for Account On-boarding.
* @author            : Satish Tiware(satish.tiware@skinternational.com).
* @last modified on  : 10th Oct 2023.
* @last modified by  : Satish Tiware(satish.tiware@skinternational.com).
**/

public with sharing class DistributorOnboardingController {
    
    /** 
    * @description : Create Distributor Documents and related file using AccountId,file parameters and record parameters.
    * @param       : recName,recDescription,base64Data,fileName,recId 
    * @return      : returns Singke created Distributor Document Record.
    **/   
        @AuraEnabled
        public static String createRecWithFile(String formFile) {
    
             RecWithfileWrapperClass recWithfileWrapperClassObj = (RecWithfileWrapperClass)JSON.deserialize(formFile,RecWithfileWrapperClass.class);
            
             Distributor_Document__c.sObjectType.getDescribe().isCreateable();
             Distributor_Document__c distributorDoc = new Distributor_Document__c (Distributor__c = recWithfileWrapperClassObj.recId,
                                                                                  Name = recWithfileWrapperClassObj.recName,
                                                                                  Document_Type__c = recWithfileWrapperClassObj.recName,
                                                                                  Description__c = recWithfileWrapperClassObj.recDescription
                                                                                 );
            
            insert distributorDoc;
           
          
            ContentVersion.sObjectType.getDescribe().isCreateable();
            ContentVersion contentVersionRec = new ContentVersion();  
            contentVersionRec.Title = recWithfileWrapperClassObj.fileName.subStringBeforeLast('.');  
            contentVersionRec.PathOnClient = recWithfileWrapperClassObj.fileName;  
            contentVersionRec.VersionData = EncodingUtil.base64Decode(recWithfileWrapperClassObj.base64Data);  
            contentVersionRec.IsMajorVersion = true;  
            Insert contentVersionRec;  
            
            Id conDoc = [SELECT ContentDocumentId FROM ContentVersion WHERE Id =:contentVersionRec.Id].ContentDocumentId;
            
            ContentDocumentLink.sObjectType.getDescribe().isCreateable();
            ContentDocumentLink conDocLink = New ContentDocumentLink();
            conDocLink.LinkedEntityId = distributorDoc.Id; 
            conDocLink.ContentDocumentId = conDoc;  
            conDocLink.shareType = 'V';
            try {
                insert conDocLink;
            } 
            catch(DMLException e) {
                System.debug(e);
                return null;
            }
            return distributorDoc.Id;
            
        }    
    
        
        
        
    /**
    * @description : Fetching DistributorDocument records using respective Account Id.
    * @param       : accountId 
    * @return      : returns DistributorDocument records Details.
    **/   
        @AuraEnabled
        public static List<Distributor_Document__c> getRecords(String accountId) {
            
           
            List<Distributor_Document__c> docList = [SELECT Id, Name,Distributor__c,Distributor__r.Name,Description__c 
                                                     FROM Distributor_Document__c 
                                                     where Distributor__c =:accountId WITH SECURITY_ENFORCED];
            
            return docList;
        }
        
        
    /**
    * @description : Fetching ContentVersion record using respective DistributorDocument Id.
    * @param       : distributorDocID 
    * @return      : returns ContentVersion records Details
    **/   
        @AuraEnabled
        public static ContentVersion getContentDetails(String distributorDocID) {
            
            ContentDocumentLink.SObjectType.getDescribe().isAccessible();
            List<ContentDocumentLink> contentDocumentList = [SELECT ContentDocumentId, LinkedEntityId 
                                                             FROM   ContentDocumentLink 
                                                             WHERE  LinkedEntityId =: distributorDocID];
            Set<Id> contentDocumentId = new Set<Id>();
            
            for(ContentDocumentLink cdl : contentDocumentList){
                contentDocumentId.add(cdl.ContentDocumentId);
                
                
            }
            
            ContentVersion contentVersionList = [SELECT Id, VersionData, FileType, Title, FileExtension,
                                                 ContentDocument.CreatedBy.Name, ContentDocument.ContentSize,
                                                 CreatedDate, ContentDocumentId, ContentDocument.FileType
                                                 FROM   ContentVersion 
                                                 WHERE  ContentDocumentId IN : contentDocumentId WITH SECURITY_ENFORCED LIMIT 1];
            if(contentVersionList != null){
                return contentVersionList;
            }else
            {
                return null;
            }
            
        }
        
    /**
    * @description : Fetching Custom Metadata record i.e.KYC_Doc_Configuration__mdt.
    * @param       : No 
    * @return      : returns KYC_Doc_Configuration__mdt records Details
    **/   
        @AuraEnabled(Cacheable=true)
        public static List<String> mandatoryFiles(){
            
            KYC_Doc_Configuration__mdt.SObjectType.getDescribe().isAccessible();
            KYC_Doc_Configuration__mdt kycDoc = [SELECT Id, DeveloperName, Value__c 
                                                 FROM KYC_Doc_Configuration__mdt
                                                 WHERE DeveloperName ='Account_KYC' LIMIT 1];
            
            List<String> str = String.valueOf(kycDoc.Value__c).split(',');
            
            return str;
        }
    
        public class RecWithfileWrapperClass
        {
            @AuraEnabled
            public string recId{get;set;} 
    
            @AuraEnabled
            public string recName{get;set;}
    
            @AuraEnabled
            public string recDescription{get;set;}
    
            @AuraEnabled
            public string base64Data{get;set;}
    
            @AuraEnabled
            public string fileName{get;set;}
    
        }
    }