force-app/main/default/objects/Distributor_Document__c/Distributor_Document__c.object-meta.xml
<CustomObject>
    <label>Distributor Document</label>
    <nameField>
        <label>Distributor Document Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Distributor Documents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Distributor_Document__c/fields/Distributor__c.field-meta.xml
<CustomField>
    <fullName>Distributor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Distributor</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Distributor Documents</relationshipLabel>
    <relationshipName>Distributor_Documents</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/DistributorDocumentSelector.cls
public without Sharing class  DistributorDocumentSelector extends LibSObjectSelector{
    public Schema.SObjectType getSObjectType(){
        return Distributor_Document__c.SObjectType;
    }
    
    public List<Schema.SObjectField> getSObjectFieldList(){
        return new List<Schema.SObjectField> {
            Distributor_Document__c.Id,
                Distributor_Document__c.Name,
                Distributor_Document__c.Distributor__c,
                Distributor_Document__c.Distributor__r.Name,
                Distributor_Document__c.Description__c
                };
                    }
    
    public List<Distributor_Document__c> getRecords(String accountId){
        LibQueryFactory query = newQueryFactory();
        query.setCondition('Distributor__c =:accountId');
        System.debug('Query is'+query.toSOQL());
        return Database.query( query.toSOQL());    
    }
}